#!/usr/bin/env python

import signal, sys

import sip
sip.setapi('QVariant', 2)

from PyQt4.QtGui import QApplication
from qmpclib.qmpcapp import QMPCApp

def main():
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    a = QApplication(sys.argv)
    a.setApplicationName("qmpc")
    a.setOrganizationName("mechnich")
    a.setStyleSheet("QStatusBar, QStatusBar *, QMenuBar,ClickableLabel { background-color: black; color: white }")
    q = QMPCApp()
    return a.exec_()

if __name__ == "__main__":
    main()
